//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManagementSystem_
{
    using System;
    using System.Collections.Generic;
    
    public partial class IssueBook
    {
        public string StudentName { get; set; }
        public string Department { get; set; }
        public string Semester { get; set; }
        public string ContactNo { get; set; }
        public string Email { get; set; }
        public string BookName { get; set; }
        public string BookIssueDate { get; set; }
        public string BookReturnDate { get; set; }
    }
}
